################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/aiSystemPerformance.c \
D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/aiTestHelper.c \
D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/aiTestUtility.c \
D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/ai_device_adaptor.c \
D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/app_x-cube-ai.c \
D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/lc_print.c \
D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/network.c \
D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/network_data.c \
D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/network_data_params.c \
D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/syscalls.c 

OBJS += \
./App/aiSystemPerformance.o \
./App/aiTestHelper.o \
./App/aiTestUtility.o \
./App/ai_device_adaptor.o \
./App/app_x-cube-ai.o \
./App/lc_print.o \
./App/network.o \
./App/network_data.o \
./App/network_data_params.o \
./App/syscalls.o 

C_DEPS += \
./App/aiSystemPerformance.d \
./App/aiTestHelper.d \
./App/aiTestUtility.d \
./App/ai_device_adaptor.d \
./App/app_x-cube-ai.d \
./App/lc_print.d \
./App/network.d \
./App/network_data.d \
./App/network_data_params.d \
./App/syscalls.d 


# Each subdirectory must supply rules for building sources it contributes
App/aiSystemPerformance.o: D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/aiSystemPerformance.c App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H562xx -c -I../Core/Inc -IC:/Users/nicek/Desktop/CMSIS-DSP/Include -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/CMSIS/Core/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/dsp" -IC:/Users/nicek/STM32Cube/Repository//Packs/STMicroelectronics/X-CUBE-ALGOBUILD/1.4.0/Middlewares/Third_Party/ARM/DSP/Inc -ID:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/App -I"D:/Smart_OnDevice/SmartDevice/smart_device/Middlewares/ST/AI/Inc" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
App/aiTestHelper.o: D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/aiTestHelper.c App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H562xx -c -I../Core/Inc -IC:/Users/nicek/Desktop/CMSIS-DSP/Include -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/CMSIS/Core/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/dsp" -IC:/Users/nicek/STM32Cube/Repository//Packs/STMicroelectronics/X-CUBE-ALGOBUILD/1.4.0/Middlewares/Third_Party/ARM/DSP/Inc -ID:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/App -I"D:/Smart_OnDevice/SmartDevice/smart_device/Middlewares/ST/AI/Inc" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
App/aiTestUtility.o: D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/aiTestUtility.c App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H562xx -c -I../Core/Inc -IC:/Users/nicek/Desktop/CMSIS-DSP/Include -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/CMSIS/Core/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/dsp" -IC:/Users/nicek/STM32Cube/Repository//Packs/STMicroelectronics/X-CUBE-ALGOBUILD/1.4.0/Middlewares/Third_Party/ARM/DSP/Inc -ID:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/App -I"D:/Smart_OnDevice/SmartDevice/smart_device/Middlewares/ST/AI/Inc" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
App/ai_device_adaptor.o: D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/ai_device_adaptor.c App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H562xx -c -I../Core/Inc -IC:/Users/nicek/Desktop/CMSIS-DSP/Include -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/CMSIS/Core/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/dsp" -IC:/Users/nicek/STM32Cube/Repository//Packs/STMicroelectronics/X-CUBE-ALGOBUILD/1.4.0/Middlewares/Third_Party/ARM/DSP/Inc -ID:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/App -I"D:/Smart_OnDevice/SmartDevice/smart_device/Middlewares/ST/AI/Inc" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
App/app_x-cube-ai.o: D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/app_x-cube-ai.c App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H562xx -c -I../Core/Inc -IC:/Users/nicek/Desktop/CMSIS-DSP/Include -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/CMSIS/Core/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/dsp" -IC:/Users/nicek/STM32Cube/Repository//Packs/STMicroelectronics/X-CUBE-ALGOBUILD/1.4.0/Middlewares/Third_Party/ARM/DSP/Inc -ID:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/App -I"D:/Smart_OnDevice/SmartDevice/smart_device/Middlewares/ST/AI/Inc" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
App/lc_print.o: D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/lc_print.c App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H562xx -c -I../Core/Inc -IC:/Users/nicek/Desktop/CMSIS-DSP/Include -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/CMSIS/Core/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/dsp" -IC:/Users/nicek/STM32Cube/Repository//Packs/STMicroelectronics/X-CUBE-ALGOBUILD/1.4.0/Middlewares/Third_Party/ARM/DSP/Inc -ID:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/App -I"D:/Smart_OnDevice/SmartDevice/smart_device/Middlewares/ST/AI/Inc" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
App/network.o: D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/network.c App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H562xx -c -I../Core/Inc -IC:/Users/nicek/Desktop/CMSIS-DSP/Include -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/CMSIS/Core/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/dsp" -IC:/Users/nicek/STM32Cube/Repository//Packs/STMicroelectronics/X-CUBE-ALGOBUILD/1.4.0/Middlewares/Third_Party/ARM/DSP/Inc -ID:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/App -I"D:/Smart_OnDevice/SmartDevice/smart_device/Middlewares/ST/AI/Inc" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
App/network_data.o: D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/network_data.c App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H562xx -c -I../Core/Inc -IC:/Users/nicek/Desktop/CMSIS-DSP/Include -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/CMSIS/Core/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/dsp" -IC:/Users/nicek/STM32Cube/Repository//Packs/STMicroelectronics/X-CUBE-ALGOBUILD/1.4.0/Middlewares/Third_Party/ARM/DSP/Inc -ID:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/App -I"D:/Smart_OnDevice/SmartDevice/smart_device/Middlewares/ST/AI/Inc" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
App/network_data_params.o: D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/network_data_params.c App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H562xx -c -I../Core/Inc -IC:/Users/nicek/Desktop/CMSIS-DSP/Include -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/CMSIS/Core/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/dsp" -IC:/Users/nicek/STM32Cube/Repository//Packs/STMicroelectronics/X-CUBE-ALGOBUILD/1.4.0/Middlewares/Third_Party/ARM/DSP/Inc -ID:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/App -I"D:/Smart_OnDevice/SmartDevice/smart_device/Middlewares/ST/AI/Inc" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
App/syscalls.o: D:/Smart_OnDevice/SmartDevice/STM32H573I-DK/X-CUBE-AI/App/syscalls.c App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H562xx -c -I../Core/Inc -IC:/Users/nicek/Desktop/CMSIS-DSP/Include -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/CMSIS/Core/Include" -I"C:/Users/nicek/Desktop/CMSIS-DSP/Include/dsp" -IC:/Users/nicek/STM32Cube/Repository//Packs/STMicroelectronics/X-CUBE-ALGOBUILD/1.4.0/Middlewares/Third_Party/ARM/DSP/Inc -ID:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/App -I"D:/Smart_OnDevice/SmartDevice/smart_device/Middlewares/ST/AI/Inc" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI" -I"D:/Smart_OnDevice/SmartDevice/smart_device/X-CUBE-AI/Target" -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.5.0/Drivers/CMSIS/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Device/ST/STM32H5xx/Include -IC:/Users/nicek/STM32Cube/Repository/STM32Cube_FW_H5_V1.2.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-App

clean-App:
	-$(RM) ./App/aiSystemPerformance.cyclo ./App/aiSystemPerformance.d ./App/aiSystemPerformance.o ./App/aiSystemPerformance.su ./App/aiTestHelper.cyclo ./App/aiTestHelper.d ./App/aiTestHelper.o ./App/aiTestHelper.su ./App/aiTestUtility.cyclo ./App/aiTestUtility.d ./App/aiTestUtility.o ./App/aiTestUtility.su ./App/ai_device_adaptor.cyclo ./App/ai_device_adaptor.d ./App/ai_device_adaptor.o ./App/ai_device_adaptor.su ./App/app_x-cube-ai.cyclo ./App/app_x-cube-ai.d ./App/app_x-cube-ai.o ./App/app_x-cube-ai.su ./App/lc_print.cyclo ./App/lc_print.d ./App/lc_print.o ./App/lc_print.su ./App/network.cyclo ./App/network.d ./App/network.o ./App/network.su ./App/network_data.cyclo ./App/network_data.d ./App/network_data.o ./App/network_data.su ./App/network_data_params.cyclo ./App/network_data_params.d ./App/network_data_params.o ./App/network_data_params.su ./App/syscalls.cyclo ./App/syscalls.d ./App/syscalls.o ./App/syscalls.su

.PHONY: clean-App

